// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Source: App/Views/Auth/ForgotPassword.tsx
import ViewComponent from 'App/Views/Auth/ForgotPassword.tsx'
import { usePageContext } from 'vike-react/usePageContext'

// Cast to a permissive component type — controller-supplied props are validated
// at the call site (view('id', props)), not in this generated stub.
const View = ViewComponent as unknown as (props: Record<string, unknown>) => JSX.Element

export default function Page() {
  const ctx = usePageContext() as unknown as { viewProps?: Record<string, unknown> }
  const props = ctx.viewProps ?? {}
  return <View {...props} />
}
