// AUTO-GENERATED by @rudderjs/vite — do not edit.
// Forwards controller-supplied viewProps from server SSR to client hydration.
import type { Config } from 'vike/types'

export default {
  passToClient: ['viewProps'],
} satisfies Config
